### ISSUE TITLE
BetterStack

### ISSUE THREAD

**Issue by joscha** [PipedreamHQ/pipedream#11821]
**Name of app / service**

BetterStack incident / log / uptime management

**Link to developer documentation**

https://betterstack.com/docs/uptime/api/getting-started-with-uptime-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

I can use their REST API for now

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Trigger incident alerts is the main one

**Comment by joscha** [comment]
This app is partially available as `BetterUptime` with a beta flag in the Pipedream Apps. The API endpoints are outdated.

**Comment by malexanderlim** [comment]
@joscha I've archived the `BetterUptime` app and now `BetterStack` is live, along with the ability to create, acknowledge, or resolve an incident:
https://pipedream.com/apps/better-stack

**Comment by joscha** [comment]
@malexanderlim it seems any API requests are now consistently failing with
```json
{"errors":"Invalid Team API token. How to find your Team API token: https://betterstack.com/docs/uptime/api/getting-started-with-better-uptime-api#obtaining-a-better-uptime-api-token"}
```
The configuration I am using is:
```js
Authorization: `Bearer ${this.better_stack.$auth.api_key}`,
```

Hardcoding the value of `this.better_stack.$auth.api_key` makes it work. It seems only the autocomplete integration part is not correct for some reason, it suggests `api_key` and `oauth_access_token` for me:
<img width="600" alt="Alert_on_unknown_public_pages_-_Build_-_Pipedream" src="https://github.com/PipedreamHQ/pipedream/assets/188038/b0db7c1c-45c9-4e4e-8a6e-e468318a3167">

but the correct value is actually in the `.uptime_token` property.

**Comment by malexanderlim** [comment]
Hi Joscha,

Can you try reconnecting your account? We've recently made a change to
support multiple token types. If you reconnect your account with the
appropriate token types, this should be fixed.

Best,
Michael

**Comment by malexanderlim** [comment]
Are you using one of our registry actions? I was able to test just now without issue.

If you're using code steps, you'll need to use:
`Authorization: `Bearer ${this.better_stack.$auth.uptime_token` as this was changed from `api_key` to `uptime_token`.

**Comment by joscha** [comment]
Hi,

Yes as stated in my previous post I found the right property the token is kept in, but only by introspection on the object, the auto complete was still showing me the outdated properties, hence why it took a while to find and why my code didn't work immediately.

**Comment by malexanderlim** [comment]
Got it - thanks for flagging. I've opened up a feature request internally to support retrieving the $auth dynamically, as `api_key` and `oauth_access_tokens` are set as defaults currently.
