### ISSUE TITLE
[BUG] Discord New Message source fails to emit all new messages

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1220]
I'm intermittently failing to receive all of the new messages posted to the channels I'm watching in the Discord **New Message** event source.

**Comment by dylburger** [comment]
This should be fixed.

**Comment by Chikanz** [comment]
Hey I'm still having issues with this - seems like it's only catching every other message for me. Any ideas?

**Comment by dylburger** [comment]
@Chikanz would you mind trying now? We rolled out a fix that should address this. Apologies for the continued issues.

**Comment by Chikanz** [comment]
@dylburger Working great now, thanks!

**Comment by dylburger** [comment]
This should be fixed.
