### ISSUE TITLE
[BUG] Rate limit error message not scrollable 

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#1656]
**Describe the bug**
I got a rate limit error (shown in the left hand list of executions), but it also reported an error on top as well, but it was above the highest I could scroll.

This is latest MS Edge, Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/393660/132073520-1e9e5e1b-e384-4efe-bce6-0d83b737744d.png)

**Comment by cfjedimaster** [comment]
If I select that execution in my history, the problem persists.

**Comment by cfjedimaster** [comment]
A complete reload fixes it though. 

![image](https://user-images.githubusercontent.com/393660/132073659-0f9691e9-52c0-4021-8f69-c7ed674d0c1e.png)

**Comment by dylburger** [comment]
@cfjedimaster just to confirm, are you no longer seeing this issue anymore after hard refreshing the site? We fixed a related issue just around the time you reported, so I think you may have been seeing it just before the fix was deployed.

**Comment by cfjedimaster** [comment]
Looks fixed. I reloaded, viewed the past execution and it was good. I clicked a few others and came back, still good.

**Comment by cfjedimaster** [comment]
I'm still seeing this (and accidentally posted the issue in the wrong thread):

Ok, I don't think this is fixed. I'm clicking around more, and it seems like the problem returns when there is a msg of some sort on top. This time it was the gray 'you are viewing a' something or another, the message letting you know it's an old thing. In the screenshot below, you can see it's "stuck" above the fold. I was able to see it once, but returned and it's unreachable.

![image](https://user-images.githubusercontent.com/393660/132239284-e4580f6c-f958-4611-b69e-a31be4e582b6.png)

As I click around after this, the top in general is now cut off:

![image](https://user-images.githubusercontent.com/393660/132239314-1dadd3fe-f267-4ba3-a2ba-b94423fbc152.png)

Maybe the fix you did for an error message on top also needs to be applied to the gray message?

**Comment by dylburger** [comment]
@cfjedimaster would you mind sharing this specific workflow with dylan@pipedream.com? Can you also select the event from the event inspector on the left where you're seeing this issue? When you select an event, we append the ?e query string parameter with the event ID, so I can take a look at the same event data that you are, which will help me reproduce the issue.

We may have fixed in Chrome and not in Edge, so I'm looking into that, too.

**Comment by cfjedimaster** [comment]
I've shared, but now I'm not sure how to trigger the gray message. I can select old executions, but I'm not sure how to get the warning to come up.

**Comment by cfjedimaster** [comment]
Ah - had to go older. And I can recreate it - but not terribly consistently. I had to pick the oldest execution I could to get the 'broken grey' thing up on top. I can make a video if need be.

**Comment by dylburger** [comment]
Yes if you don't mind, a video would be great!

**Comment by dylburger** [comment]
Actually I was able to reproduce by clicking the last event, as you noted. Looking into it.

**Comment by cfjedimaster** [comment]
Uploaded here - I *just* pushed this up so maybe give it a minute, but it's only 22 seconds long so it shouldn't take much longer to be ready: https://www.youtube.com/watch?v=F5FAd-utl_Q

**Comment by cfjedimaster** [comment]
Oh heh, missed your comment. Well, enjoy. :)

**Comment by dylburger** [comment]
@cfjedimaster great thank you. Can you try to hard refresh your browser (clearing pipedream.com cache) one more time and see if it's fixed for you?

**Comment by cfjedimaster** [comment]
This does seem to have fixed it. I'm seeing another issue (and it seems at least close to the original, so adding it here). In the history column, the text is cut off:

![image](https://user-images.githubusercontent.com/393660/132341113-119ba452-c59e-4195-bbf6-37b62e8160af.png)

**Comment by dannyroosevelt** [comment]
@cfjedimaster thanks for surfacing that issue with the event getting cutoff -- we just pushed out a fix for this!
