### ISSUE TITLE
[BUG] Saleforce Access Tokens not reliably refreshing

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4222]
User report:
>Just recently (in the past few weeks) I noticed the refresh token process for my Salesforce REST API connection stopped working.  In order to get any workflow that uses Salesforce REST API to complete, I need to reconnect my Salesforce REST API connection (which I think issues a new access token good for 2 hrs).

> This issue actually started for me September 2 and has been persisting since.  I last reconnected my Salesforce REST API account this morning about 3 hrs ago and requests now return as unauthorized again.

Reported via Slack https://pipedream-users.slack.com/archives/CPTJYRY5A/p1662645705821619

**Comment by dylburger** [comment]
This has been fixed.

**Comment by mickmw** [comment]
I'm still seeing 401 errors on my Salesforce REST account. 
errorCode:
INVALID_SESSION_ID
message:
Session expired or invalid

Let me know if you need more info.
